services:
  s3mock:
    image: adobe/s3mock:latest
    container_name: s3mock
    ports:
      - "9090:9090"
      - "9191:9191"
    environment:
      COM_ADOBE_TESTING_S3MOCK_STORE_INITIAL_BUCKETS: "test"
      debug: "true"
